### ISSUE TITLE
ZBase.Foundation.Mvvm.Unity.ViewBinding.MonoBinder  Reduce GC

### ISSUE THREAD

**Issue by eefan000** [Zitga-Tech/ZBase.Foundation.Mvvm#1]
FindNearestContext does not require 'new List<IBindingContext>()'

**Comment by grashaar** [comment]
Fixed in https://github.com/Zitga-Tech/ZBase.Foundation.Mvvm/commit/a4ce7ffaf6a6d749cd92c09fbec8a0e409970a67
