### ISSUE TITLE
Can we use the Unity Unsafe Utility to replace Unsafe

### ISSUE THREAD

**Issue by eefan000** [Zitga-Tech/ZBase.Foundation.Mvvm#5]
This can reduce dependence
https://docs.unity3d.com/ScriptReference/Unity.Collections.LowLevel.Unsafe.UnsafeUtility.html

**Comment by grashaar** [comment]
It's not possible because `UnsafeUtility.SizeOf` only work for structs.

**Comment by grashaar** [comment]
Fixed in 1.4.2
